print(getwd())
setwd("/home/basit/Desktop/R")
print(getwd())
data <- read.csv("avg_ratings1.csv")
print(data)
print(is.data.frame(data))
print(nrow(data))
sal <- max(data$rating)
print(sal)
retval <-subset(data,book_id ==10)
print(retval)
mean.value = mean(data$rating)
print(mean.value)
median.value = median(data$rating)
print(median.value)
print(mean(data$rating,trim = .3))
stand <-sd(data$rating)
print(stand)
print(var(data$rating))
print(range(data$rating))
retval <-subset(data,book_id >10 & book_id< 15)
print(retval)
write.csv(retval,"mycsv.csv")